### ISSUE TITLE
undefined: ibmmq.MQCNO after upgrading to golang 1.21.1

### ISSUE THREAD

**Issue by Sparkz0629** [ibm-messaging/mq-golang-jms20#68]
Hi.

We are busy with a golang upgrade from 1.15 to 1.21.1 across our microservices

One of the services uses the mq-golang-jms20 module.

When attempting to build the code in the new env, we get the following:

```
# github.com/ibm-messaging/mq-golang-jms20/jms20subset
/go/pkg/mod/github.com/ibm-messaging/mq-golang-jms20@v1.11.0/jms20subset/MQOptions.go:5:32: undefined: ibmmq.MQCNO
/go/pkg/mod/github.com/ibm-messaging/mq-golang-jms20@v1.11.0/jms20subset/MQOptions.go:8:25: undefined: ibmmq.MQCNO
```

this is our build stage:

```
build:
  stage: build
  only:
    refs:
    - master
  image: ${BUILD_IMAGE}
  script:
    - mkdir -p /opt/mqm
    - chmod a+rx /opt/mqm
    - export genmqpkg_incnls=1
    - export genmqpkg_incsdk=1
    - export genmqpkg_inctls=1
    - cp 9.2.4.0-IBM-MQC-Redist-LinuxX64.tar.gz /opt/mqm/
    - tar -zxf /opt/mqm/*.tar.gz
    - rm -f /opt/mqm/*.tar.gz
    - export LD_LIBRARY_PATH=.:/opt/mqm/lib64:/opt/mqm/java/lib64:$LIBPATH
    - export PATH=.:/opt/mqm/bin:$PATH
    - bin/genmqpkg.sh -b /opt/mqm
    - img build -t ${DOCKER_PUSH_URL}/mq-transfer-server:2.0 --build-arg GO_IMAGE=${GO_121_IMAGE}  .
    - echo "build done"
    - echo ${ENCODED_PASSWORD} | base64 -d | img login --username ${USER} --password-stdin ${DOCKER_PUSH_URL}
    - img push ${DOCKER_PUSH_URL}/mq-transfer-server:2.0
    - img logout ${DOCKER_PUSH_URL}
```

where GO_121_IMAGE is an image built from the below with our certificates added.

```
FROM golang:1.21.1-bookworm
ENV GOOS=linux 
ENV GOARCH=amd64 
ENV CGO_ENABLED=0 
```

BUILD_IMAGE is `FROM debian:12.1-slim` with our certificates added.

Looking for any advised or assistance on the above... out of 15 microservices, this is the only one that we are stuck on the upgrade with. (Also the only one to use to mq libraries)
